#test execution script.

language: java
jdk:
  - oraclejdk8
sudo: false
before_cache:
  - du -h -d 2 $HOME/.m2/
  - find $HOME/.m2 -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.m2
install:
  - mkdir installers && curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar > installers/jpm4j.jar
  - java -jar installers/jpm4j.jar -u init && rm -r installers && export PATH=$PATH:$HOME/jpm/bin
  - jpm install com.codacy:codacy-coverage-reporter:assembly
script:
  - mvn clean test
after_success:
  - mvn -Dcoveralls.repo.token=$COVERALLS_REPO_TOKEN jacoco:report coveralls:report
  - mvn --settings=updateimpactsettings.xml updateimpact:submit
  - bash <(curl -s https://codecov.io/bash)
  - codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml --prefix src/main/java/
