#test execution script.

language: java
jdk:
  - oraclejdk8
sudo: false
before_cache:
  - du -h -d 2 $HOME/.m2/
  - find $HOME/.m2 -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean test
after_success:
  - mvn -Dcoveralls.repo.token=$COVERALLS_REPO_TOKEN jacoco:report coveralls:report
  - mvn updateimpact:submit
  - bash <(curl -s https://codecov.io/bash)
