comment:
  layout: header, changes, diff
coverage:
  status:
    patch:
      default:
        branches:
        - '!\[wip\]*'
        target: '80'
    project:
      default:
        branches:
        - '!\[wip\]*'
        target: auto
